apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-native-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ChaninduImanjith/cloud-native-devops-platform.git'
    targetRevision: HEAD
    path: kubernetes
    directory:
      recurse: true # This makes Argo CD look inside all subdirectories (hpa, storage, etc.)
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
