services:

  backend:
    image: chaninduimanjith/cloud-native-devops-backend:latest
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: chaninduimanjith/cloud-native-devops-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge