apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-native-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "chaninduimanjith.com"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - chaninduimanjith.com
    secretName: cloud-native-tls
  rules:
  - host: chaninduimanjith.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
